name: Deploy Quarto site to GitHub Pages

on:
  push:
    branches:
      - main  # se ejecuta al hacer push a main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 'latest'

      # 3. Instalar dependencias si las hay
      - name: Install dependencies
        run: |
          quarto install

      # 4. Renderizar el sitio
      - name: Render Quarto site
        run: |
          quarto render

      # 5. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # carpeta generada por Quarto
